Lab4: HDRI2Cubemap and irradiance map
sergeevgk/CG_2021 pull request #3
Opened 2021-05-10 19:14 UTC by sergeevgk

2021-05-17 06:42 UTC, anthark requested changes
Почти все правильно. Три момента, которые надо исправить: 
1) Неправильно работает ambient компонента - слишком яркий цвет в результате
2) При интегрировании получаются артефакты - нужно взять HDR картинку с меньшим динамическим диапазоном, не extremly high
3) Конфликты с main веткой

2021-05-19 09:23 UTC, anthark requested changes

2021-05-19 09:23 UTC, anthark commented on ComputerGraphicsProject/Shaders.fx
> +    float e = Exposure()*exposureMult;
Не, проблема не здесь. Так вы меняете яркость всей картинки целиком, а у вас проблема в ambient() компоненте PBR

2021-05-19 10:39 UTC, sergeevgk commented on ComputerGraphicsProject/Shaders.fx
> +    float e = Exposure()*exposureMult;
Исправили ambient, теперь код такой же, как в презентации. Логически и визуально ничего не поменялось, в чем заключалась проблема с ambient компонентой?

2021-05-19 12:35 UTC, anthark commented on ComputerGraphicsProject/Shaders.fx
> +    float e = Exposure()*exposureMult;
Какой смысл имеет эта строчка?

float3 color = colorBase.rgb;

2021-05-19 14:04 UTC, sergeevgk commented on ComputerGraphicsProject/Shaders.fx
> +    float e = Exposure()*exposureMult;
Похоже, мы забыли убрать эту компоненту с 3 лабораторной работы. Действительно, с ней цвет получается не таким, как должен быть.

2021-05-19 14:07 UTC, anthark commented on ComputerGraphicsProject/Shaders.fx
> +    float e = Exposure()*exposureMult;
ОК, теперь правильно. Задача засчитана.

2021-05-19 14:07 UTC, merged